### ISSUE TITLE
Removed from BlackBerry world?

### ISSUE THREAD

**Issue by hrnr** [amonchakai/Hg10#120]
Hi,
I can not see Hg10 in the BlackBerry world any more. Was the app removed on a purpose?

**Comment by amonchakai** [comment]
Yes, I am tiered to give my own time for free and getting bad reviews. So I am done.

There are builds in the release section if you are interested in Hg10.

**Comment by hrnr** [comment]
I understand that. Thanks anyway for this piece of software.

**Comment by akm2016** [comment]
Hi ,Unable to see hg10 in blackberry world .Need to install in blackberry,may i know the location

**Comment by hrnr** [comment]
see above. There is `.bar` available for latest release, that works but it is 80 commits behind. Or build from source. In both cases you'll need some developer experience.

**Comment by amonchakai** [comment]
Hi,

It is there: https://github.com/amonchakai/Hg10/releases

And no, it is not 80 commits behind. Only 1 actually. 

If you take this one:  Hg10-1_4_2_187.bar
The version number is meant as:
1: it is a release which was on the store
4: this number was increased when there is change I considered as big. 
2: this number was increased after a small fix. 
187: is the version number on github. If you clone the repository to this version, you get the corresponding build.

I just chose to update the file in the release section, and not create a new version every time. But there is a pre-release legacy with several previous build if you like.

**Comment by akm2016** [comment]
```
                                                                                  HiThanksI don't have developer knowledge Also when I try to open. Bar file is not getting openPlease advise me                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: amonchakaiSent: Saturday 2 April 2016 12:51 AMTo: amonchakai/Hg10Reply To: amonchakai/Hg10Cc: akm2016Subject: Re: [amonchakai/Hg10] Removed from BlackBerry world? (#120)Hi,
```

It is there: https://github.com/amonchakai/Hg10/releases

And no, it is not 80 commits behind. Only 1 actually. 

If you take this one:  Hg10-1_4_2_187.bar
The version number is meant as:
1: it is a release which was on the store
4: this number was increased when there is change I considered as big. 
2: this number was increased after a small fix. 
187: is the version number on github. If you clone the repository to this version, you get the corresponding build.

I just chose to update the file in the release section, and not create a new version every time. But there is a pre-release legacy with several previous build if you like. 

—You are receiving this because you commented.Reply to this email directly or view it on GitHub

**Comment by amonchakai** [comment]
You need to sideload the application, see:
http://crackberry.com/sideload-apps-your-blackberry-using-google-chrome

It is written for Android applications, but that the process you should do for a .bar file

**Comment by hrnr** [comment]
@amonchakai nice, I didn't noticed that attached file is actually newer than release.

**Comment by akm2016** [comment]
Hi

Thanks for your information.
It helped me and installation done successfully.
Let me know if any updates in future.

Thanks and Regards

Ajin Kumar.M
09442364008

**Comment by akm2016** [comment]
Hi

Suddenly hg10 stopped getting chat messages.
Is there any bug ..

Thanks and Regards

Ajin Kumar.M
09442364008

**Comment by akm2016** [comment]
HiPlease let me know if any fixed version released                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Ajin KumarSent: Monday 2 May 2016 6:14 PMTo: amonchakai/Hg10Cc: amonchakai/Hg10Subject: Re: [amonchakai/Hg10] Removed from BlackBerry world? (#120)HiSuddenly hg10 stopped getting chat messages.Is there any bug ..Thanks and RegardsAjin Kumar.M09442364008
On Sat, Apr 2, 2016 at 8:53 PM, Ajin Kumar <ajinmca@gmail.com> wrote:Hi Thanks for your information.It helped me and installation done successfully.Let me know if any updates in future.Thanks and RegardsAjin Kumar.M09442364008
On Sat, Apr 2, 2016 at 6:17 PM, amonchakai <notifications@github.com> wrote:You need to sideload the application, see:
http://crackberry.com/sideload-apps-your-blackberry-using-google-chrome

It is written for Android applications, but that the process you should do for a .bar file

—You are receiving this because you commented.Reply to this email directly or view it on GitHub
