### ISSUE TITLE
Cannot connect to Facebook

### ISSUE THREAD

**Issue by foudamo** [amonchakai/Hg10#3]
So I have been trying to connect to Facebook (https://www.facebook.com/sitetour/chat.php) but without any success. I am using the correct info, and the app authenticates correctly; however it gets stuck at loading after this without anything else developing. I have attached a screenshot on the screen I get stuck at. 
[App Version: 1.1.1.82]
[Phone: Q10 - 10.3.1.1154 ]
![img_20141225_231517](https://cloud.githubusercontent.com/assets/6817956/5555743/94deed18-8c8c-11e4-8af0-d63d71ad056b.png)

**Comment by amonchakai** [comment]
Hi,

Sorry for the late reply, I did not noticed this issue. I just tried it, and it seems to be working for me.

Did you saw the manual after trying to connect? That should indicate you if the connection has been successful or not. If you close the application, and restart it before it managed to connect, then you may be stuck on the page you are currently viewing. 

Since you reported that bug 10 days ago, I guess you already uninstalled the application. In case you would want to try again, I would recommend you to check the setttings of facebook whether it is not blocking the app'. That would be the main reason for connection failure (assuming your login / password are correct). 

For Facebook, I am aware that I should rather use facebook login than the "old" XMPP login, which should solve such issues. But since Facebook is planning to close the XMPP service end of April (see the text in the red box there: https://developers.facebook.com/docs/chat ) I am not sure it is worth for me to spend too much time on this...

**Comment by foudamo** [comment]
Hi again, 

Sorry for the late reply. I do get the manual screen after connecting. However, I don't see the app on the Facebook>Settings>Apps screen. It doesn't show any record of being blocked or anything. 

Any ideas of how to check that?

**Comment by amonchakai** [comment]
Hi,

OK, if you can see the manual, that is already something. 

Some idea for finding the problem would be to go to settings, enable the log option, click on save, and try to close & open the app again. Then you can have a look into the logs, just to check if you see some familiar names or nothing meaningful for you. 

The idea would be to identify if it is a problem with my application or Facebook blocking it. 

I currently do not use the Facebook login, and that is why you cannot see this application in the Facebook settings... And that is also why they may block it. 

Maybe I will find the time to work on that during the week to solve this issue. I should just use the Facebook login, there is not so much things to do since I already implemented most of the things needed...
