### ISSUE TITLE
Help me please witch GH10-master (BugReport)

### ISSUE THREAD

**Issue by Gh10User** [amonchakai/Hg10#39]
Hi, I want to deploy my app Github forum for bugs and input, you could help me because I have an error I get GITHUB_ACCESS_TOKEN was no token of declared in esta

**Comment by marcossit-dev** [comment]
![captura](https://cloud.githubusercontent.com/assets/11509340/7380385/4ca124ae-edc5-11e4-8208-58bc66b187b4.PNG)
this error

**Comment by amonchakai** [comment]
Hi!

Sure. The issue you have, is I did not included one file "PrivateAPIKey.h" which I don't share because it defines the keys I got from Google, github, dropbox and so on. And I obviously don't want people to use my keys. 

To get a key, I just created another account 'Gh10User', then go to personal access token. Create one. And then it is this token which is behind the github_access_token macro.

If you want, I have a much simpler project than Hg10 for only the github integration. You can find it there: https://github.com/amonchakai/Gh10

**Comment by marcossit-dev** [comment]
Thanks already got my key and achieve Github use the file, but present an inconvenience, I want that when a user comment does not leave them my Github Nick, quit them a nick and your app (Guetsxxx)

**Comment by amonchakai** [comment]
Ah and regarding the error with 'BugReport', just go to the build menu, then clean. I may have committed intermediate build object...

**Comment by amonchakai** [comment]
Yes, that is why I created another account than mine: Gh10User. 
And I had to put this new account as a collaborator, so it can add labels.

**Comment by marcossit-dev** [comment]
perfect as the 2nd thinks my name has UserGuetsxxx and associate the Token to the project, but does not create the input sends an internal message me nothing more.

**Comment by marcossit-dev** [comment]
thanks Fixed and running smoothly integrated in my application: D thanks

For the future could you edit the code to post pictures or share images, and if you can create the custom user.

**Comment by amonchakai** [comment]
Great ! 

I was thinking about this issue of posting images, but I think it is not available yet though the api of github. At least that is what I read the last time I checked.

I would also be nice to let people use their own github account, if they have one.

And no, I won't distribute the github user. It is not difficult to create one.

**Comment by amonchakai** [comment]
Issue closed.
