### ISSUE TITLE
files attachment 

### ISSUE THREAD

**Issue by monkeyshoulder** [amonchakai/Hg10#48]
Hi!
Many thanks for creating this useful program! A lot of my friends use Hangouts on their Samsungs so thanks to you we are always online from now on.
But I've got a question about files attachment. When I send a photo to my 'Samsung' friend, I somehow send it as a link which leads to a file on google account. So I see this file sent as a link and my friend receives a link which leads to the picture. 
The same thing with receiving photos. When my friends sends a picture to me, he attaches file and send it but I receive the link to this file. 
It's not difficult at all to follow the link to get the picture but still, is there any chance to receive not the link but file attached?
If it helps, I use Blackberry Classic 

Thank you for you help!

**Comment by amonchakai** [comment]
Hi!
Yes, it is true, there is this issue which need to be solved. 

The thing is I am using google drive to share pictures which is different than what google does. It seems it is something based on Google+ but somehow different, and I haven't found a way to reproduce what they do. So that is why your friends on Android see only a link... The one from Google Drive.

For the other direction, e.g.. when an Android user share a picture with you, I get this URL from Google+ (apparently somehow stored on picassa from my research). But I haven't found a way to get the picture behind this link automatically (yet).

This is something which annoy me, so you can be sure that I am working on it :P

**Comment by amonchakai** [comment]
Done!
