### ISSUE TITLE
Messages disappear

### ISSUE THREAD

**Issue by Gh10User** [amonchakai/Hg10#54]
Messages with specific contact disappear after one second, and instead the history from ages ago is loaded

**Comment by Gh10User** [comment]
This just happened to me as well. Message history wouldn't load for weeks until I sent a new message, which is now completely gone. The messages (there were more than one) disappeared when switching from the hub to the app itself, though I'm not sure switching had any impact. Also, the contact I sent the message to and from are Google Hangouts contacts. I haven't experienced this before with other Hangouts clients.

**Comment by amonchakai** [comment]
I guess it must be a connection issue to the server. I may have solved it. 
An update will be available soon.

**Comment by MagnusOxlund** [comment]
I'm experiencing this problem a lot. Sometime the messages just aren't displayed in the app, but are delivered. Other times, the messages I send just disappear when I hit the send button. I've noticed that the reload button also might clear any recently sent messages from the chat.

**Comment by amonchakai** [comment]
I also noticed that issue. I just pushed a fix to the store to address this. 
I wanted to package it with other fixes, but since it make some time I have that fix ready and did not find the time to fix the other stuff, I think it may be better that I just push a small update to only address this problem.
