### ISSUE TITLE
Contacts showing up as long address of numbers and letters after edit.

### ISSUE THREAD

**Issue by Gh10User** [amonchakai/Hg10#68]
I edited some of my contacts information on my computer because they were showing up multiple times in my contact list, but now there are multiple contacts showing up as an adress@talk.google.com and they are all long series of numbers and letter.

**Comment by z3rogate** [comment]
I have the Same "issue" ...                                                                                                                                                                                                                                                                                                                                         Gesendet von meinem BlackBerry 10-Smartphone.                                                                                                                                                                                                                Von: Bug Report ClientGesendet: Sonntag, 5. Juli 2015 05:01An: amonchakai/Hg10Antwort an: amonchakai/Hg10Betreff: [Hg10] Contacts showing up as long address of numbers and letters after edit. (#68)I edited some of my contacts information on my computer because they were showing up multiple times in my contact list, but now there are multiple contacts showing up as an adress@talk.google.com and they are all long series of numbers and letter.

—Reply to this email directly or view it on GitHub.

**Comment by amonchakai** [comment]
It is solved in the next release which should appear early next week

**Comment by amonchakai** [comment]
The release which fix this is available on the store.
