### ISSUE TITLE
Blackberry Passport - Sign in works, contact list too but can't do anything

### ISSUE THREAD

**Issue by jamesst20** [amonchakai/Hg10#7]
Hi,

I am able to sign in with my Google account and then see my conversations. However, conversations can't be opened, nothing happens when I click them. 

The 3 buttons that appear on top by dragging down such as settings does nothing. The left menu contains Drive and contacts but clicking them has no effect aswell... 

Change status, mark read, add contact does nothing to.

The only thing that works is the listview scrolling.

Blackberry OS 10.3.0.1418

**Comment by jamesst20** [comment]
Tested BBWorld version and the 2 releases on GitHub. They all suffer from the same issue.

**Comment by amonchakai** [comment]
Uh, that is very strange... 
It is like all NavigationPane are not working... 
I will have a look if I find how could that happens, but I cannot really promise anything. Since it is so unexpected...

**Comment by jamesst20** [comment]
Thanks you, please let me know :)                                                                                                                                                                                                                                                                           Envoyé de mon smartphone BlackBerry 10 sur le réseau Virgin Mobile.                                                                                                                                                                                                                De: amonchakaiEnvoyé: mardi 3 février 2015 04:11À: amonchakai/Hg10Répondre à: amonchakai/Hg10Cc: jamesst20Objet: Re: [Hg10] Blackberry Passport - Sign in works, contact list too but can't do anything (#7)Uh, that is very strange... 
It is like all NavigationPane are not working... 
I will have a look if I find how could that happens, but I cannot really promise anything. Since it is so unexpected...

—Reply to this email directly or view it on GitHub.

**Comment by jamesst20** [comment]
I have installed 10.3.1.2243 leak and the build of yesterday and it's loading indefinitely after adding permissions to Google account. Unable to get a contact list but at least the UI works now

**Comment by amonchakai** [comment]
Hi,

Could you try the version: Hg10-1_2_2_141 (10.3.0 with NO hub) that you can find there:
https://github.com/amonchakai/Hg10/releases/tag/1

**Comment by jamesst20** [comment]
Hi,

I am sorry, I couldn't try it this weekend. However good news! Installed today's version from the Blackberry world (9 February) and the application works flawless! Still on leak 10.3.1.2243!

One annoying thing I could see is that it doesn't support group conversation. At first I though there was a bug because it was displaying same messages in 3 friend's conversation but I realized it was sent in a group. 

Thanks you !

**Comment by amonchakai** [comment]
Hi,

Ok, that is cool that it finally workout. Eventhough that version have no difference with the one you tried out on the release section... 

But if it is working, that good!

Regarding group chat, I know there is something to be done there. I haven't managed to make it works. 
I have some idea for example I could try to use Blink ( http://www.chromium.org/blink ). which would allow me to use the Hangout extension and would open the door to group chat, video & audio.

I don't know how realistic it is to try to embded it inside Hg10... At least a better handling of the history is something which could be easily solved.

So for now, I will close this issue. Since apparently it is solved. Feel free to open it again if you see any problems.
